# Generated by Django 5.1.2 on 2025-01-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdftomp3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='mp3',
        ),
        migrations.DeleteModel(
            name='pdf',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
