# Generated by Django 5.1.2 on 2025-01-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdftomp3', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mp3',
            new_name='MP3File',
        ),
        migrations.RenameModel(
            old_name='pdf',
            new_name='PDFFile',
        ),
    ]
